### ISSUE TITLE
not geting any feedback reports

### ISSUE THREAD

**Issue by skidrv911** [Git-Lukyen/LoL_AutoReport#2]
so far ive played games and reported around 50 people and didint get a single feedback report of someone geting punished. maybe it automaticly blacklists you or something

**Comment by Git-Lukyen** [comment]
I get report feedbacks almost daily and I only report through the script... I don't know what to tell you but for me and some other people it works

**Comment by skidrv911** [comment]
maybe its because i am chat restricted myself, thanks for the quick response though

**Comment by skidrv911** [comment]
now the report script stopped working  and nit gives me those errors, https://pastebin.com/5tbGX7tC tried reinstalling python didint help ;(
